package org.apache.jsp.jsp.blueprint;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class blueprint1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<title>网工－培养方案</title>\r\n");
      out.write("<link href=\"/css/main.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"/css/blueprint.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!--头部header-->\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/jsp/include/header.jsp", out, true);
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<!--//header-->\r\n");
      out.write("<!--主体容器container-->\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("  <!--内容区content，包括菜单和主内容-->\r\n");
      out.write("  <div class=\"content\">\r\n");
      out.write("    <!--左边内容框leftContentFrame-->\r\n");
      out.write("    <div class=\"leftContentFrame\">\r\n");
      out.write("      <!--左边菜单框leftMenuFrame-->\r\n");
      out.write("      <div class=\"leftMenuFrame\">\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/jsp/include/leftMenu.jsp", out, true);
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("      <!--//leftMenuFrame-->\r\n");
      out.write("      <div class=\"imgLinksFrame\">\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/jsp/include/imgLinks.jsp", out, true);
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"customLinksFrame\">\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/jsp/include/customLinks.jsp", out, true);
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--右边内容框rightContentFrame-->\r\n");
      out.write("    <div class=\"rightContentFrame\">\r\n");
      out.write("      <div class=\"breadcrumbs\"> <a href=\"/\">首页</a> &nbsp;&gt;&nbsp;培养方案 </div>\r\n");
      out.write("      <div id = \"blueprintFrame\">\r\n");
      out.write("        <h1>计算机科学系网络工程专业本科培养方案</h1>\r\n");
      out.write("        <p style=\"font-family: '楷体_GB2312'; font-size: 14px; text-align: center; color: #F60;\">（2009级）</p>\r\n");
      out.write("        <h2>一、培养目标</h2>\r\n");
      out.write("        <p>培养德、智、体、美、劳全面发展，系统掌握本专业的基本理论、基础知识和基本技能与方法，能够胜任工程开发和科学研究工作的具有良好综合素质和开拓创新能力的高级网络人才。</p>\r\n");
      out.write("        <h2>二、学制与学位授予</h2>\r\n");
      out.write("        <p>本科学制四年。对完成并符合本科培养方案要求的学生授予工学学士学位。 </p>\r\n");
      out.write("        <h2>三、基本学分学时</h2>\r\n");
      out.write("        <p>本科培养总学分不少于160。公共必修（含数学分析）46学分、专业必修（含毕业论文）63学分、选修（含人文选修课）57学分。其中，春、秋季学期课程总学分不少于140，夏季学期实践环节（含军事教育）不少于12学分，毕业论文/设计8学分。 </p>\r\n");
      out.write("        <h2>四、课程结构与学分要求</h2>\r\n");
      out.write("        <ol>\r\n");
      out.write("          <li>人文社会科学类课程：51学分，必修35学分，选修16学分</li>\r\n");
      out.write("        </ol>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li>文、史、政、哲：（5门） 16学分：</li>\r\n");
      out.write("          <table border=\"1px\">\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"150\">思想道德修养</td>\r\n");
      out.write("              <td width=\"74\">3学分</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"150\" >毛、邓概论及“三个代表”</td>\r\n");
      out.write("              <td width=\"74\" >6学分</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"150\" >马克思主义基本原理</td>\r\n");
      out.write("              <td width=\"74\" >3学分</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"150\" >中国近代史纲要</td>\r\n");
      out.write("              <td width=\"74\" >2学分</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"150\" >大学语文</td>\r\n");
      out.write("              <td width=\"74\" >2学分</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("          </table>\r\n");
      out.write("          <br />\r\n");
      out.write("          <li>体育课：（1门 ）4学分：分1-4学期，每学期1学分。</li>\r\n");
      out.write("          <br />\r\n");
      out.write("          <li>外语课：（1门）12学分：分1-4学期，每学期3学分。</li>\r\n");
      out.write("          <br />\r\n");
      out.write("          <li>其它：（2门）3学分：</li>\r\n");
      out.write("          <table border=\"1px\">\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"150\" >形式与政策</td>\r\n");
      out.write("              <td width=\"74\" >2学分</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"150\" >就业指导</td>\r\n");
      out.write("              <td width=\"74\" >1学分</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("          </table>\r\n");
      out.write("          <br />\r\n");
      out.write("          <li>人文选修课：16学分：（可以用专业选修课代替）。</li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <ol start=\"2\">\r\n");
      out.write("          <li>自然科学基础课程：36 学分（保研需修满36学分）</li>\r\n");
      out.write("        </ol>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li>数学：（6门）29学分，必修24学分，选修5学分：</li>\r\n");
      out.write("          <table border=\"1\" width=\"301\">\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"150\" >数学分析I</td>\r\n");
      out.write("              <td width=\"74\" >5学分</td>\r\n");
      out.write("              <td width=\"55\" >必修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"150\" >数学分析II</td>\r\n");
      out.write("              <td width=\"74\" >4学分</td>\r\n");
      out.write("              <td width=\"55\" >必修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"150\" >高等代数</td>\r\n");
      out.write("              <td width=\"74\" >5学分</td>\r\n");
      out.write("              <td width=\"55\" >必修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"150\" >集合论与图论</td>\r\n");
      out.write("              <td width=\"74\" >4学分</td>\r\n");
      out.write("              <td width=\"55\" >必修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"150\" >概率论与数理统计</td>\r\n");
      out.write("              <td width=\"74\" >3学分</td>\r\n");
      out.write("              <td width=\"55\" >必修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"150\" >数理逻辑</td>\r\n");
      out.write("              <td width=\"74\" >3学分</td>\r\n");
      out.write("              <td width=\"55\" >必修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"150\" >代数结构</td>\r\n");
      out.write("              <td width=\"74\" >2学分</td>\r\n");
      out.write("              <td width=\"55\" >选修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"150\" >数值计算方法</td>\r\n");
      out.write("              <td width=\"74\" >3学分</td>\r\n");
      out.write("              <td width=\"55\" >选修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("          </table>\r\n");
      out.write("          <br />\r\n");
      out.write("          <li>物理：（21门）7学分，必修：</li>\r\n");
      out.write("          <table border=\"1\">\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"150\" >大学物理I</td>\r\n");
      out.write("              <td width=\"74\" >4学分</td>\r\n");
      out.write("              <td width=\"55\" >必修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"150\" >大学物理II</td>\r\n");
      out.write("              <td width=\"74\" >3学分</td>\r\n");
      out.write("              <td width=\"55\" >必修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("          </table>\r\n");
      out.write("          <br />\r\n");
      out.write("        </ul>\r\n");
      out.write("        <ol start=\"3\">\r\n");
      out.write("          <li>IT平台基础课程：18学分，15学分必修，3学分选修（保研需修满18学分）</li>\r\n");
      out.write("        </ol>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <table border=\"1\">\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"150\" >程序设计I</td>\r\n");
      out.write("              <td width=\"74\" >3学分</td>\r\n");
      out.write("              <td width=\"55\" >必修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"150\" >程序设计I实验</td>\r\n");
      out.write("              <td width=\"74\" >1学分</td>\r\n");
      out.write("              <td width=\"55\" >必修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"150\" >数据结构与算法</td>\r\n");
      out.write("              <td width=\"74\" >3学分</td>\r\n");
      out.write("              <td width=\"55\" >必修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"150\" >数据结构与算法实验</td>\r\n");
      out.write("              <td width=\"74\" >1学分</td>\r\n");
      out.write("              <td width=\"55\" >必修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"150\" >数字电路与逻辑设计</td>\r\n");
      out.write("              <td width=\"74\" >3学分</td>\r\n");
      out.write("              <td width=\"55\" >必修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"150\" >数字电路与逻辑设计实验</td>\r\n");
      out.write("              <td width=\"74\" >1学分</td>\r\n");
      out.write("              <td width=\"55\" >必修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"150\" >信号与系统</td>\r\n");
      out.write("              <td width=\"74\" >3学分</td>\r\n");
      out.write("              <td width=\"55\" >必修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"150\" >电路与电子学</td>\r\n");
      out.write("              <td width=\"74\" >2学分</td>\r\n");
      out.write("              <td width=\"55\" >选修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"150\" >电路与电子学实验</td>\r\n");
      out.write("              <td width=\"74\" >1学分</td>\r\n");
      out.write("              <td width=\"55\" >选修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("          </table>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <ol start=\"4\">\r\n");
      out.write("          <li>专业技术课程</li>\r\n");
      out.write("        </ol>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li>专业基础课：（14门）31学分，必修16学分，选修15学分。（保研、参评奖学金需修满31学分）：</li>\r\n");
      out.write("          <table border=\"1px\">\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"150\" >程序设计II</td>\r\n");
      out.write("              <td width=\"74\" >2学分</td>\r\n");
      out.write("              <td width=\"55\" >必修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"150\" >程序设计II实验</td>\r\n");
      out.write("              <td width=\"74\" >1学分</td>\r\n");
      out.write("              <td width=\"55\" >必修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"150\" >计算机组成原理</td>\r\n");
      out.write("              <td width=\"74\" >4学分</td>\r\n");
      out.write("              <td width=\"55\" >必修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"150\" >计算机组成原理实验</td>\r\n");
      out.write("              <td width=\"74\" >1学分</td>\r\n");
      out.write("              <td width=\"55\" >必修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"150\" >操作系统原理</td>\r\n");
      out.write("              <td width=\"74\" >3学分</td>\r\n");
      out.write("              <td width=\"55\" >必修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"150\" >操作系统原理实验</td>\r\n");
      out.write("              <td width=\"74\" >1学分</td>\r\n");
      out.write("              <td width=\"55\" >必修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"150\" >计算机网络</td>\r\n");
      out.write("              <td width=\"74\" >3学分</td>\r\n");
      out.write("              <td width=\"55\" >必修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"150\" >计算机网络实验</td>\r\n");
      out.write("              <td width=\"74\" >1学分</td>\r\n");
      out.write("              <td width=\"55\" >必修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"150\" >计算机接口技术及实践</td>\r\n");
      out.write("              <td width=\"74\" >2学分</td>\r\n");
      out.write("              <td width=\"55\" >选修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"150\" >编译原理及实践</td>\r\n");
      out.write("              <td width=\"74\" >4学分</td>\r\n");
      out.write("              <td width=\"55\" >选修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"150\" >软件工程导论及实践</td>\r\n");
      out.write("              <td width=\"74\" >3学分</td>\r\n");
      out.write("              <td width=\"55\" >选修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"150\" >数据库系统原理及实践</td>\r\n");
      out.write("              <td width=\"74\" >3学分</td>\r\n");
      out.write("              <td width=\"55\" >选修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"150\" >人工智能及实践</td>\r\n");
      out.write("              <td width=\"74\" >3学分</td>\r\n");
      out.write("              <td width=\"55\" >选修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("          </table>\r\n");
      out.write("          <p><strong><font color=\"#FF0000\">注:&nbsp;&nbsp;&nbsp;</font></strong>核心课程群的实验课必须与理论课同时选或同时不选，不能只选实验课或只选理论课。</p>\r\n");
      out.write("          <li>专业技术课：</li>\r\n");
      out.write("          <table border=\"1px\">\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td colspan=\"3\" align=\"center\" bgcolor=\"#8080C0\">专选公共课</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"150\" >通信原理</td>\r\n");
      out.write("              <td width=\"74\" >2学分</td>\r\n");
      out.write("              <td width=\"55\" >选修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"150\" >无线通信与网络</td>\r\n");
      out.write("              <td width=\"74\" >2学分</td>\r\n");
      out.write("              <td width=\"55\" >选修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"150\" >密码学与网络安全</td>\r\n");
      out.write("              <td width=\"74\" >2学分</td>\r\n");
      out.write("              <td width=\"55\" >选修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"150\" >密码学与网络安全实验</td>\r\n");
      out.write("              <td width=\"74\" >1学分</td>\r\n");
      out.write("              <td width=\"55\" >选修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"150\" >计算机网络主题讲座</td>\r\n");
      out.write("              <td width=\"74\" >2学分</td>\r\n");
      out.write("              <td width=\"55\" >选修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("          </table>\r\n");
      out.write("          <br />\r\n");
      out.write("          <table border=\"1px\">\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td colspan=\"3\" align=\"center\" bgcolor=\"#8080C0\">专选A（网络管理方向）</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"150\" >网络优化与网络管理</td>\r\n");
      out.write("              <td width=\"74\" >2学分</td>\r\n");
      out.write("              <td width=\"55\" >选修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"150\" >网络优化与网络管理实验</td>\r\n");
      out.write("              <td width=\"74\" >1学分</td>\r\n");
      out.write("              <td width=\"55\" >选修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"150\" >网络存储技术及实践</td>\r\n");
      out.write("              <td width=\"74\" >3学分</td>\r\n");
      out.write("              <td width=\"55\" >选修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"150\" >网络处理器与网络系统设计</td>\r\n");
      out.write("              <td width=\"74\" >2学分</td>\r\n");
      out.write("              <td width=\"55\" >选修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("          </table>\r\n");
      out.write("          <br />\r\n");
      out.write("          <table border=\"1px\">\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td colspan=\"3\" align=\"center\" bgcolor=\"#8080C0\">专选B（网络编程方向）</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"150\" >网络协议分析与设计</td>\r\n");
      out.write("              <td width=\"74\" >2学分</td>\r\n");
      out.write("              <td width=\"55\" >选修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"150\" >Web信息检索</td>\r\n");
      out.write("              <td width=\"74\" >2学分</td>\r\n");
      out.write("              <td width=\"55\" >选修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"150\" >并行与分布式计算</td>\r\n");
      out.write("              <td width=\"74\" >2学分</td>\r\n");
      out.write("              <td width=\"55\" >选修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"150\" >电子商务</td>\r\n");
      out.write("              <td width=\"74\" >2学分</td>\r\n");
      out.write("              <td width=\"55\" >选修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("          </table>\r\n");
      out.write("          <p><strong><font color=\"#FF0000\">注:&nbsp;&nbsp;&nbsp;</font></strong>专业选修课的实验课必须与理论课同时选或同时不选，不能只选实验课或只选理论课。建议选择专选公共课和一到两门的其它专选课。可以根据兴趣按方向（专选A，专选B）选择。</p>\r\n");
      out.write("          <li>其它选修课：</li>\r\n");
      out.write("          <table border=\"1px\">\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"151\" >多核程序设计及实践</td>\r\n");
      out.write("              <td width=\"74\" >3学分</td>\r\n");
      out.write("              <td width=\"56\" >选修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"151\" >高级数据库技术及实践</td>\r\n");
      out.write("              <td width=\"74\" >2学分</td>\r\n");
      out.write("              <td width=\"56\" >选修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"151\" >工作流技术</td>\r\n");
      out.write("              <td width=\"74\" >2学分</td>\r\n");
      out.write("              <td width=\"56\" >选修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"151\" >计算机图形学</td>\r\n");
      out.write("              <td width=\"74\" >2学分</td>\r\n");
      out.write("              <td width=\"56\" >选修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"151\" >数字图像处理</td>\r\n");
      out.write("              <td width=\"74\" >2学分</td>\r\n");
      out.write("              <td width=\"56\" >选修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"151\" >模式识别</td>\r\n");
      out.write("              <td width=\"74\" >2学分</td>\r\n");
      out.write("              <td width=\"56\" >选修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"151\" >数据挖掘</td>\r\n");
      out.write("              <td width=\"74\" >2学分</td>\r\n");
      out.write("              <td width=\"56\" >选修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"151\" >虚拟现实</td>\r\n");
      out.write("              <td width=\"74\" >2学分</td>\r\n");
      out.write("              <td width=\"56\" >选修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"151\" >多媒体技术</td>\r\n");
      out.write("              <td width=\"74\" >2学分</td>\r\n");
      out.write("              <td width=\"56\" >选修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"151\" >算法设计与应用</td>\r\n");
      out.write("              <td width=\"74\" >2学分</td>\r\n");
      out.write("              <td width=\"56\" >选修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"151\" >智能算法及应用</td>\r\n");
      out.write("              <td width=\"74\" >2学分</td>\r\n");
      out.write("              <td width=\"56\" >选修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"151\" >形式语言与自动机</td>\r\n");
      out.write("              <td width=\"74\" >2学分</td>\r\n");
      out.write("              <td width=\"56\" >选修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"151\" >计算机体系结构</td>\r\n");
      out.write("              <td width=\"74\" >2学分</td>\r\n");
      out.write("              <td width=\"56\" >选修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"151\" >人机交互设计</td>\r\n");
      out.write("              <td width=\"74\" >2学分</td>\r\n");
      out.write("              <td width=\"56\" >选修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"151\" >嵌入式系统原理与应用</td>\r\n");
      out.write("              <td width=\"74\" >2学分</td>\r\n");
      out.write("              <td width=\"56\" >选修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"151\" >信息科学技术导论</td>\r\n");
      out.write("              <td width=\"74\" >2学分</td>\r\n");
      out.write("              <td width=\"56\" >选修</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("          </table>\r\n");
      out.write("          <p><strong><font color=\"#FF0000\">注:&nbsp;&nbsp;&nbsp;</font></strong><br />\r\n");
      out.write("            &diams;&nbsp;&nbsp;还可以选择信科院其他专业的专业基础课、专业技术课和实践课程，以及本校其他自然科学基础课。选择外校或外系的课程(应事先向教学办公室申请)。<br />\r\n");
      out.write("            &diams;&nbsp;&nbsp;学生需在数学类课程、专业基础课、专业技术课以及人文选修课的选修课中选修<strong>不少于51学分</strong>。专业技术课程都是选修课，保研时的成绩排名不计算这些课程的绩点。<br />\r\n");
      out.write("            &diams;&nbsp;&nbsp;专业技术课程的开设将根据师资情况和社会需求进行调整与更新。 </p>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <ol start=\"5\">\r\n");
      out.write("          <li>实践环节：≥11学分</li>\r\n");
      out.write("        </ol>\r\n");
      out.write("        <ul>\r\n");
      out.write("          <table border=\"1px\">\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"263\" >军事理论与技能训练</td>\r\n");
      out.write("              <td width=\"173\" >2学分 （4周）（必修）</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"263\" >网络工程专业综合实践</td>\r\n");
      out.write("              <td width=\"173\" >3学分 （4周）（必修）</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"263\" >数学建模训练</td>\r\n");
      out.write("              <td width=\"173\" >1学分 </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"263\" >数据结构与程序设计综合实践</td>\r\n");
      out.write("              <td width=\"173\" >2学分 </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"263\" >网络与操作系统综合实践</td>\r\n");
      out.write("              <td width=\"173\" >2学分 </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"263\" >生产实习与社会实践</td>\r\n");
      out.write("              <td width=\"173\" >2学分</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"263\" >自主实践（包括学科竞赛、科技活动、创新实践活动、科研项目等）</td>\r\n");
      out.write("              <td width=\"173\" >有一定成果，可得创新学分（2学分）</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("          </table>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <ol start=\"6\">\r\n");
      out.write("          <li>毕业论文/设计：8学分</li>\r\n");
      out.write("        </ol>\r\n");
      out.write("        <h2>五、说明</h2>\r\n");
      out.write("        <ol style=\" font-family:Arial, '宋体'; font-size:12px; color:#000; font-weight:normal;\">\r\n");
      out.write("          <li>公共必修（含数学分析）46学分、专业必修（含毕业论文）63学分、选修51学分。</li>\r\n");
      out.write("          <br />\r\n");
      out.write("          <li>实验实践课程学分设置共39学分：专业必修实验课7学分、军事教育2学分、专业必修综合实践3学分、其他可选实验实践课程27学分。</li>\r\n");
      out.write("          <br />\r\n");
      out.write("          <li>除人文社会科学类的必修课35学分外，保研和参评奖学金同学的其他类必修课程共计85学分（不含毕业论文）。</li>\r\n");
      out.write("          <br />\r\n");
      out.write("          <li>教学计划和培养方案主要参照学校：斯坦福大学 。</li>\r\n");
      out.write("          <br />\r\n");
      out.write("        </ol>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--//rightContentFrame-->\r\n");
      out.write("  </div>\r\n");
      out.write("  <!--content-->\r\n");
      out.write("</div>\r\n");
      out.write("<!--container-->\r\n");
      out.write("<!--底部bottom-->\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/jsp/include/footer.jsp", out, true);
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<!--//bottom-->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
